name: FS22 to FS25 Auto Sync

on:
  push:
    branches:
      - main

jobs:
  convert-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy FS22 files to FS25 (excluding ZIPs)
        run: |
          rsync -av --exclude='*.zip' ./ ./FS25/

      - name: Convert FS22 to FS25
        run: |
          rm -rf FS25
          cp -r FS22 FS25

          # Update XML version and descVersion
          sed -i 's/descVersion="66"/descVersion="80"/g' FS25/modDesc.xml
          sed -i 's/<version>1\.3\.2\.0<\/version>/<version>1.5.0.0<\/version>/g' FS25/modDesc.xml

          # Replace all FS22 references and text
          find FS25 -type f -exec sed -i 's/Farming Simulator 22/Farming Simulator 25/g' {} +
          find FS25 -type f -exec sed -i 's/FS22_/FS25_/g' {} +

          # Rename inner mod folder name for FS25
          if [ -d "FS25/FS22_CriderGPTHelper" ]; then
            mv FS25/FS22_CriderGPTHelper FS25/FS25_CriderGPTHelper
          fi

      - name: Rebuild ZIPs
        run: |
          zip -r build/FS22_CriderGPTHelper_v1.5.0.0.zip FS22/
          zip -r build/FS25_CriderGPTHelper_v1.5.0.0.zip FS25/FS25_CriderGPTHelper

      - name: Log conversion
        run: |
          mkdir -p logs
          echo "[OK] Converted FS22 → FS25 (descVersion 66 → 80)" > logs/env_convert.log
          echo "[UPDATE] Version bumped to 1.5.0.0" >> logs/env_convert.log
          echo "[ZIP] FS22_CriderGPTHelper_v1.5.0.0.zip and FS25_CriderGPTHelper_v1.5.0.0.zip built" >> logs/env_convert.log
          echo "[DONE] FS25 files and metadata synced successfully." >> logs/env_convert.log

      - name: Commit and push FS25 changes
        run: |
          git config user.name "CriderGPT Auto Sync"
          git config user.email "actions@github.com"
          git checkout -B fs25_version
          git add FS25
          git commit -m "Synced FS22 → FS25 environment (v${NEW_VERSION})" || echo "No changes to commit."
          git push origin fs25_version --force
